//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int Id { get; set; }
        public int UserId { get; set; }
    
        public virtual UserData UserData { get; set; }
        public virtual UserData ContactData { get; set; }
        public virtual NotRegisteredContacts NotRegisteredContacts { get; set; }
    }
}
