//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contacts> Contacts { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<EventTemplates> EventTemplates { get; set; }
        public DbSet<Folders> Folders { get; set; }
        public DbSet<Languages> Langs { get; set; }
        public DbSet<Properties> Properties { get; set; }
        public DbSet<PropertiesValuesBool> PropertiesValuesBool { get; set; }
        public DbSet<PropertiesValuesDateTime> PropertiesValuesDateTime { get; set; }
        public DbSet<PropertiesValuesImages> PropertiesValuesImages { get; set; }
        public DbSet<PropertiesValuesInt> PropertiesValuesInt { get; set; }
        public DbSet<PropertiesValuesString> PropertiesValuesString { get; set; }
        public DbSet<PropertyTypes> PropertyTypes { get; set; }
        public DbSet<StringNames> StringNames { get; set; }
        public DbSet<StringsLocalization> StringsLocalization { get; set; }
        public DbSet<UserData> UserData { get; set; }
        public DbSet<UserProperties> UserProperties { get; set; }
        public DbSet<NotRegisteredContacts> NotRegisteredContacts { get; set; }
        public DbSet<NotRegisteredContactsProperties> NotRegisteredContactsProperties { get; set; }
        public DbSet<ContactsSummary> ContactsSummary { get; set; }
        public DbSet<Images> Images { get; set; }
    }
}
