//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTemplates
    {
        public EventTemplates()
        {
            this.Event = new HashSet<Event>();
            this.Properties = new HashSet<Properties>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Properties> Properties { get; set; }
        public virtual UserData UserData { get; set; }
        public virtual Images Images { get; set; }
    }
}
