//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotRegisteredContacts
    {
        public NotRegisteredContacts()
        {
            this.NotRegisteredContactsProperties = new HashSet<NotRegisteredContactsProperties>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual ICollection<NotRegisteredContactsProperties> NotRegisteredContactsProperties { get; set; }
    }
}
