//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public Properties()
        {
            this.PropertiesValuesBool = new HashSet<PropertiesValuesBool>();
            this.PropertiesValuesDateTime = new HashSet<PropertiesValuesDateTime>();
            this.PropertiesValuesImages = new HashSet<PropertiesValuesImages>();
            this.PropertiesValuesInt = new HashSet<PropertiesValuesInt>();
            this.PropertiesValuesString = new HashSet<PropertiesValuesString>();
            this.EventTemplates = new HashSet<EventTemplates>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
    
        public virtual PropertyTypes PropertyTypes { get; set; }
        public virtual ICollection<PropertiesValuesBool> PropertiesValuesBool { get; set; }
        public virtual ICollection<PropertiesValuesDateTime> PropertiesValuesDateTime { get; set; }
        public virtual ICollection<PropertiesValuesImages> PropertiesValuesImages { get; set; }
        public virtual ICollection<PropertiesValuesInt> PropertiesValuesInt { get; set; }
        public virtual ICollection<PropertiesValuesString> PropertiesValuesString { get; set; }
        public virtual ICollection<EventTemplates> EventTemplates { get; set; }
    }
}
