//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StringsLocalization
    {
        public int StringId { get; set; }
        public int LangId { get; set; }
        public string LocalizedString { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual StringNames StringNames { get; set; }
    }
}
