//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public UserData()
        {
            this.Contacts = new HashSet<Contacts>();
            this.Event = new HashSet<Event>();
            this.Folders = new HashSet<Folders>();
            this.UserProperties = new HashSet<UserProperties>();
            this.Contacts1 = new HashSet<Contacts>();
            this.EventTemplates = new HashSet<EventTemplates>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string SecondName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int LangId { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual ICollection<Contacts> Contacts { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Folders> Folders { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual ICollection<UserProperties> UserProperties { get; set; }
        public virtual ICollection<Contacts> Contacts1 { get; set; }
        public virtual ICollection<EventTemplates> EventTemplates { get; set; }
        public virtual Images Images { get; set; }
    }
}
